name: Cargo Checkmate
description: Run cargo-checkmate to check Rust code quality

inputs:
  toolchain:
    description: Rust toolchain to use
    required: false
    default: stable
  rustflags:
    description: RUSTFLAGS passed via env
    required: false
    default: "-D warnings"
  phase:
    description: Checkmate phase to run (build, check, clippy, doc, format)
    required: true

runs:
  using: composite
  steps:
    - name: Install cargo-checkmate
      uses: taiki-e/cache-cargo-install-action@v2
      with:
        tool: cargo-checkmate

    - name: Run cargo checkmate
      shell: bash
      env:
        RUSTFLAGS: ${{ inputs.rustflags }}
      run: cargo-checkmate run ${{ inputs.phase }}
