name: Cargo Shear
description: Run cargo-shear to detect unused dependencies

inputs:
  toolchain:
    description: Rust toolchain to use
    required: false
    default: stable
  rustflags:
    description: RUSTFLAGS passed via env
    required: false
    default: "-D warnings"

runs:
  using: composite
  steps:
    - name: Install cargo-shear
      uses: taiki-e/cache-cargo-install-action@v2
      with:
        tool: cargo-shear

    - name: Run cargo-shear
      shell: bash
      env:
        RUSTFLAGS: ${{ inputs.rustflags }}
      run: cargo shear
